onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sqlite3

overrides:
  '@tootallnate/once@<3.0.1': '>=3.0.1'
  diff@<8.0.3: '>=8.0.3'
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  undici@<6.23.0: '>=6.23.0'
  uuid@<14.0.0: '>=14.0.0'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
